banks:
  SBIN:
    date_format: "%d/%m/%Y"
    narration_hints: ["NEFT", "IMPS", "RTGS"]
  IDIB:
    date_format: "%d/%m/%Y"
  HDFC:
    date_format: "%d/%m/%Y"
  KKBK:
    date_format: "%d/%m/%Y"
  MAHB:
    date_format: "%d/%m/%Y"
default:
  date_format: "%d/%m/%Y"

